name: Check memory leaks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependency
      run: |
        sudo apt-get update
        sudo apt-get -y install cmake valgrind
    - name: Build
      run: bash ci/build-and-install.sh
    - name: Test
      run: bash ci/test-memory.sh
